DESC PRODUIRE;
DESC ALERT;
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME, R_CONSTRAINT_NAME 
FROM USER_CONSTRAINTS 
WHERE R_CONSTRAINT_NAME IN (
  SELECT CONSTRAINT_NAME FROM USER_CONSTRAINTS 
  WHERE TABLE_NAME = 'MACHINE' AND CONSTRAINT_TYPE = 'P'
);
EXIT;
