--------------------------------------------------------
--  Fichier créé - mardi-avril-14-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ARTICLE
--------------------------------------------------------

  CREATE TABLE "OILPRESSTEAM"."ARTICLE" 
   (	"ID_ARTICLE" NUMBER(10,0), 
	"NOM_ARTICLE" VARCHAR2(100 BYTE), 
	"QUANTITE" NUMBER(10,0), 
	"UNITE" VARCHAR2(20 BYTE), 
	"PRIX_UNITAIRE" NUMBER(10,0), 
	"DATE_ACHAT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMANDE
--------------------------------------------------------

  CREATE TABLE "OILPRESSTEAM"."COMMANDE" 
   (	"ID_COMMANDE" NUMBER(10,0), 
	"DATE_COMMANDE" DATE, 
	"ETAT_COMMANDE" VARCHAR2(50 BYTE), 
	"NOM_CLIENT" VARCHAR2(100 BYTE), 
	"DATE_LIVRAISON" DATE, 
	"ADRESSE_CLIENT" VARCHAR2(255 BYTE), 
	"REFERENCE" VARCHAR2(20 BYTE), 
	"DELIVERY_STATUS" VARCHAR2(50 BYTE) DEFAULT 'Preparing', 
	"NUMER_TELEPHONE" VARCHAR2(20 BYTE), 
	"NUMERO_TELEPHONE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONSOMMER
--------------------------------------------------------

  CREATE TABLE "OILPRESSTEAM"."CONSOMMER" 
   (	"ID_ARTICLE" NUMBER(10,0), 
	"ID_CONTENAIR" NUMBER(10,0), 
	"QUANTITE_CONSOMMEE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONTENIR
--------------------------------------------------------

  CREATE TABLE "OILPRESSTEAM"."CONTENIR" 
   (	"ID_CONTENAIR" NUMBER(10,0), 
	"ID_COMMANDE" NUMBER(10,0), 
	"QUANTITE_DEMANDEE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FINANCE
--------------------------------------------------------

  CREATE TABLE "OILPRESSTEAM"."FINANCE" 
   (	"ID_TRANSACTION" NUMBER(10,0), 
	"MONTANT" NUMBER(15,2), 
	"DATE_TRANSACTION" DATE, 
	"TYPE_TRANSACTION" VARCHAR2(50 BYTE), 
	"MODE_PAIEMENT" VARCHAR2(50 BYTE), 
	"DESCRIPTION" CLOB, 
	"ID_COMMANDE" NUMBER(10,0), 
	"REFERENCE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("DESCRIPTION") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table INTERVENIR
--------------------------------------------------------

  CREATE TABLE "OILPRESSTEAM"."INTERVENIR" 
   (	"ID_PERSONNEL" NUMBER(10,0), 
	"ID_MACHINE" NUMBER(10,0), 
	"DATE_INTERVENTION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MACHINE
--------------------------------------------------------

  CREATE TABLE "OILPRESSTEAM"."MACHINE" 
   (	"ID_MACHINE" NUMBER(10,0), 
	"NOM_MACHINE" VARCHAR2(100 BYTE), 
	"TYPE_MACHINE" VARCHAR2(50 BYTE), 
	"ETAT_MACHINE" VARCHAR2(50 BYTE), 
	"DATEDERNIEREMAINTENANCE" DATE, 
	"HEURESFONCTIONNEMENT" NUMBER(10,0), 
	"SEUILMAINTENANCE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERSONNEL
--------------------------------------------------------

  CREATE TABLE "OILPRESSTEAM"."PERSONNEL" 
   (	"ID_PERSONNEL" NUMBER(10,0), 
	"NOM_PERSONNEL" VARCHAR2(100 BYTE), 
	"SALAIRE_BRUT" NUMBER(10,2), 
	"ADRESSE" CLOB, 
	"TEL" VARCHAR2(20 BYTE), 
	"EXPERIENCE" NUMBER(5,0), 
	"GRADE" VARCHAR2(50 BYTE), 
	"ROLE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("ADRESSE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table PRODUIRE
--------------------------------------------------------

  CREATE TABLE "OILPRESSTEAM"."PRODUIRE" 
   (	"ID_CONTENAIR" NUMBER(10,0), 
	"ID_MACHINE" NUMBER(10,0), 
	"QUANTITE_PRODUIRE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUIT
--------------------------------------------------------

  CREATE TABLE "OILPRESSTEAM"."PRODUIT" 
   (	"ID_CONTENAIR" NUMBER(10,0), 
	"DATE_PRESS" DATE, 
	"QUANTITE" NUMBER(10,0), 
	"REF" VARCHAR2(50 BYTE), 
	"VISCOSITE" VARCHAR2(50 BYTE), 
	"COULEUR" VARCHAR2(30 BYTE), 
	"TEST" VARCHAR2(100 BYTE), 
	"CAPACITE" NUMBER(10,0), 
	"ID_MACHINE" NUMBER(10,0), 
	"PRIX_UNITAIRE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into OILPRESSTEAM.ARTICLE
SET DEFINE OFF;
REM INSERTING into OILPRESSTEAM.COMMANDE
SET DEFINE OFF;
Insert into OILPRESSTEAM.COMMANDE (ID_COMMANDE,DATE_COMMANDE,ETAT_COMMANDE,NOM_CLIENT,DATE_LIVRAISON,ADRESSE_CLIENT,REFERENCE,DELIVERY_STATUS,NUMER_TELEPHONE,NUMERO_TELEPHONE) values ('1',to_date('31/03/26','DD/MM/RR'),'Pending','Yassine Hablani',to_date('05/04/26','DD/MM/RR'),'Bardo',null,'Preparing',null,null);
Insert into OILPRESSTEAM.COMMANDE (ID_COMMANDE,DATE_COMMANDE,ETAT_COMMANDE,NOM_CLIENT,DATE_LIVRAISON,ADRESSE_CLIENT,REFERENCE,DELIVERY_STATUS,NUMER_TELEPHONE,NUMERO_TELEPHONE) values ('2',to_date('05/04/26','DD/MM/RR'),'Pending','Oussema Ben Nasr',to_date('02/05/26','DD/MM/RR'),'El Ghazela','gfhd2244','Preparing',null,null);
Insert into OILPRESSTEAM.COMMANDE (ID_COMMANDE,DATE_COMMANDE,ETAT_COMMANDE,NOM_CLIENT,DATE_LIVRAISON,ADRESSE_CLIENT,REFERENCE,DELIVERY_STATUS,NUMER_TELEPHONE,NUMERO_TELEPHONE) values ('3',to_date('05/04/26','DD/MM/RR'),'Pending','Nour Ben Rhouma',to_date('02/05/26','DD/MM/RR'),'Manouba','AV23','Preparing',null,null);
Insert into OILPRESSTEAM.COMMANDE (ID_COMMANDE,DATE_COMMANDE,ETAT_COMMANDE,NOM_CLIENT,DATE_LIVRAISON,ADRESSE_CLIENT,REFERENCE,DELIVERY_STATUS,NUMER_TELEPHONE,NUMERO_TELEPHONE) values ('4',to_date('05/04/26','DD/MM/RR'),'Pending','Khdija Khdiji',to_date('29/05/26','DD/MM/RR'),'Menzah 1','AV12','Preparing',null,null);
Insert into OILPRESSTEAM.COMMANDE (ID_COMMANDE,DATE_COMMANDE,ETAT_COMMANDE,NOM_CLIENT,DATE_LIVRAISON,ADRESSE_CLIENT,REFERENCE,DELIVERY_STATUS,NUMER_TELEPHONE,NUMERO_TELEPHONE) values ('5',to_date('05/04/26','DD/MM/RR'),'Pending','Angie Hamza',to_date('11/07/26','DD/MM/RR'),'Massachaussettes','AS22','Preparing',null,null);
Insert into OILPRESSTEAM.COMMANDE (ID_COMMANDE,DATE_COMMANDE,ETAT_COMMANDE,NOM_CLIENT,DATE_LIVRAISON,ADRESSE_CLIENT,REFERENCE,DELIVERY_STATUS,NUMER_TELEPHONE,NUMERO_TELEPHONE) values ('6',to_date('02/05/26','DD/MM/RR'),'Pending','Yassine Hablani',to_date('07/06/26','DD/MM/RR'),'Bardo','IV8020','Preparing',null,'+21620149773');
Insert into OILPRESSTEAM.COMMANDE (ID_COMMANDE,DATE_COMMANDE,ETAT_COMMANDE,NOM_CLIENT,DATE_LIVRAISON,ADRESSE_CLIENT,REFERENCE,DELIVERY_STATUS,NUMER_TELEPHONE,NUMERO_TELEPHONE) values ('7',to_date('14/04/26','DD/MM/RR'),'Completed','Rayen Belhaj Yahia',to_date('01/08/26','DD/MM/RR'),'Djerba','AG32','Delivered',null,'53496959');
REM INSERTING into OILPRESSTEAM.CONSOMMER
SET DEFINE OFF;
REM INSERTING into OILPRESSTEAM.CONTENIR
SET DEFINE OFF;
REM INSERTING into OILPRESSTEAM.FINANCE
SET DEFINE OFF;
Insert into OILPRESSTEAM.FINANCE (ID_TRANSACTION,MONTANT,DATE_TRANSACTION,TYPE_TRANSACTION,MODE_PAIEMENT,ID_COMMANDE,REFERENCE) values ('1','2400',to_date('12/04/26','DD/MM/RR'),'Revenue','Cash','3',null);
REM INSERTING into OILPRESSTEAM.INTERVENIR
SET DEFINE OFF;
REM INSERTING into OILPRESSTEAM.MACHINE
SET DEFINE OFF;
Insert into OILPRESSTEAM.MACHINE (ID_MACHINE,NOM_MACHINE,TYPE_MACHINE,ETAT_MACHINE,DATEDERNIEREMAINTENANCE,HEURESFONCTIONNEMENT,SEUILMAINTENANCE) values ('1',null,null,null,null,null,null);
REM INSERTING into OILPRESSTEAM.PERSONNEL
SET DEFINE OFF;
Insert into OILPRESSTEAM.PERSONNEL (ID_PERSONNEL,NOM_PERSONNEL,SALAIRE_BRUT,TEL,EXPERIENCE,GRADE,ROLE) values ('12345678','aymen','600','23456765','40','Junior','Stock Management');
REM INSERTING into OILPRESSTEAM.PRODUIRE
SET DEFINE OFF;
REM INSERTING into OILPRESSTEAM.PRODUIT
SET DEFINE OFF;
Insert into OILPRESSTEAM.PRODUIT (ID_CONTENAIR,DATE_PRESS,QUANTITE,REF,VISCOSITE,COULEUR,TEST,CAPACITE,ID_MACHINE,PRIX_UNITAIRE) values ('1',to_date('14/04/26','DD/MM/RR'),'2','fd-97','0,9','Dark Green','a+','10','1','153');
--------------------------------------------------------
--  DDL for Index COMMANDE_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "OILPRESSTEAM"."COMMANDE_UK1" ON "OILPRESSTEAM"."COMMANDE" ("REFERENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ARTICLE_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "OILPRESSTEAM"."ARTICLE_UK1" ON "OILPRESSTEAM"."ARTICLE" ("NOM_ARTICLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FINANCE_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "OILPRESSTEAM"."FINANCE_UK1" ON "OILPRESSTEAM"."FINANCE" ("REFERENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MACHINE_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "OILPRESSTEAM"."MACHINE_UK1" ON "OILPRESSTEAM"."MACHINE" ("NOM_MACHINE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008045
--------------------------------------------------------

  CREATE UNIQUE INDEX "OILPRESSTEAM"."SYS_C008045" ON "OILPRESSTEAM"."INTERVENIR" ("ID_PERSONNEL", "ID_MACHINE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CONTENIR
--------------------------------------------------------

  ALTER TABLE "OILPRESSTEAM"."CONTENIR" ADD PRIMARY KEY ("ID_CONTENAIR", "ID_COMMANDE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUIRE
--------------------------------------------------------

  ALTER TABLE "OILPRESSTEAM"."PRODUIRE" ADD PRIMARY KEY ("ID_CONTENAIR", "ID_MACHINE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INTERVENIR
--------------------------------------------------------

  ALTER TABLE "OILPRESSTEAM"."INTERVENIR" ADD CONSTRAINT "SYS_C008045" PRIMARY KEY ("ID_PERSONNEL", "ID_MACHINE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONSOMMER
--------------------------------------------------------

  ALTER TABLE "OILPRESSTEAM"."CONSOMMER" ADD PRIMARY KEY ("ID_ARTICLE", "ID_CONTENAIR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MACHINE
--------------------------------------------------------

  ALTER TABLE "OILPRESSTEAM"."MACHINE" ADD CONSTRAINT "MACHINE_UK1" UNIQUE ("NOM_MACHINE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "OILPRESSTEAM"."MACHINE" ADD PRIMARY KEY ("ID_MACHINE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ARTICLE
--------------------------------------------------------

  ALTER TABLE "OILPRESSTEAM"."ARTICLE" ADD CONSTRAINT "ARTICLE_UK1" UNIQUE ("NOM_ARTICLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "OILPRESSTEAM"."ARTICLE" ADD PRIMARY KEY ("ID_ARTICLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PERSONNEL
--------------------------------------------------------

  ALTER TABLE "OILPRESSTEAM"."PERSONNEL" ADD PRIMARY KEY ("ID_PERSONNEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMANDE
--------------------------------------------------------

  ALTER TABLE "OILPRESSTEAM"."COMMANDE" ADD CONSTRAINT "COMMANDE_UK1" UNIQUE ("REFERENCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "OILPRESSTEAM"."COMMANDE" ADD PRIMARY KEY ("ID_COMMANDE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FINANCE
--------------------------------------------------------

  ALTER TABLE "OILPRESSTEAM"."FINANCE" ADD CONSTRAINT "FINANCE_UK1" UNIQUE ("REFERENCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "OILPRESSTEAM"."FINANCE" ADD PRIMARY KEY ("ID_TRANSACTION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUIT
--------------------------------------------------------

  ALTER TABLE "OILPRESSTEAM"."PRODUIT" ADD PRIMARY KEY ("ID_CONTENAIR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONSOMMER
--------------------------------------------------------

  ALTER TABLE "OILPRESSTEAM"."CONSOMMER" ADD CONSTRAINT "FK_CONS_ART" FOREIGN KEY ("ID_ARTICLE")
	  REFERENCES "OILPRESSTEAM"."ARTICLE" ("ID_ARTICLE") ENABLE;
  ALTER TABLE "OILPRESSTEAM"."CONSOMMER" ADD CONSTRAINT "FK_CONS_PROD" FOREIGN KEY ("ID_CONTENAIR")
	  REFERENCES "OILPRESSTEAM"."PRODUIT" ("ID_CONTENAIR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONTENIR
--------------------------------------------------------

  ALTER TABLE "OILPRESSTEAM"."CONTENIR" ADD CONSTRAINT "FK_CONT_COM" FOREIGN KEY ("ID_COMMANDE")
	  REFERENCES "OILPRESSTEAM"."COMMANDE" ("ID_COMMANDE") ENABLE;
  ALTER TABLE "OILPRESSTEAM"."CONTENIR" ADD CONSTRAINT "FK_CONT_PROD" FOREIGN KEY ("ID_CONTENAIR")
	  REFERENCES "OILPRESSTEAM"."PRODUIT" ("ID_CONTENAIR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FINANCE
--------------------------------------------------------

  ALTER TABLE "OILPRESSTEAM"."FINANCE" ADD CONSTRAINT "FK_COMMANDE" FOREIGN KEY ("ID_COMMANDE")
	  REFERENCES "OILPRESSTEAM"."COMMANDE" ("ID_COMMANDE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INTERVENIR
--------------------------------------------------------

  ALTER TABLE "OILPRESSTEAM"."INTERVENIR" ADD CONSTRAINT "FK_INT_MACH" FOREIGN KEY ("ID_MACHINE")
	  REFERENCES "OILPRESSTEAM"."MACHINE" ("ID_MACHINE") ENABLE;
  ALTER TABLE "OILPRESSTEAM"."INTERVENIR" ADD CONSTRAINT "FK_INT_PERS" FOREIGN KEY ("ID_PERSONNEL")
	  REFERENCES "OILPRESSTEAM"."PERSONNEL" ("ID_PERSONNEL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUIRE
--------------------------------------------------------

  ALTER TABLE "OILPRESSTEAM"."PRODUIRE" ADD CONSTRAINT "FK_PROD_CONT" FOREIGN KEY ("ID_CONTENAIR")
	  REFERENCES "OILPRESSTEAM"."PRODUIT" ("ID_CONTENAIR") ENABLE;
  ALTER TABLE "OILPRESSTEAM"."PRODUIRE" ADD CONSTRAINT "FK_PROD_MACH" FOREIGN KEY ("ID_MACHINE")
	  REFERENCES "OILPRESSTEAM"."MACHINE" ("ID_MACHINE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUIT
--------------------------------------------------------

  ALTER TABLE "OILPRESSTEAM"."PRODUIT" ADD CONSTRAINT "FK_MACHINE" FOREIGN KEY ("ID_MACHINE")
	  REFERENCES "OILPRESSTEAM"."MACHINE" ("ID_MACHINE") ENABLE;
