--------------------------------------------------------
--  Fichier créé - mardi-mars-31-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ARTICLE
--------------------------------------------------------

  CREATE TABLE "OILPRESSTEAM"."ARTICLE" 
   (	"ID_ARTICLE" NUMBER(10,0), 
	"NOM_ARTICLE" VARCHAR2(100 BYTE), 
	"QUANTITE" NUMBER(10,0), 
	"UNITE" VARCHAR2(20 BYTE), 
	"PRIX_UNITAIRE" NUMBER(10,0), 
	"DATE_ACHAT" NUMBER(20,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMANDE
--------------------------------------------------------

  CREATE TABLE "OILPRESSTEAM"."COMMANDE" 
   (	"ID_COMMANDE" NUMBER(10,0), 
	"DATE_COMMANDE" DATE, 
	"ETAT_COMMANDE" VARCHAR2(50 BYTE), 
	"NOM_CLIENT" VARCHAR2(100 BYTE), 
	"DATE_LIVRAISON" DATE, 
	"ADRESSE_LIVRAISON" VARCHAR2(255 BYTE), 
	"ADRESSE_CLIENT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONSOMMER
--------------------------------------------------------

  CREATE TABLE "OILPRESSTEAM"."CONSOMMER" 
   (	"ID_ARTICLE" NUMBER(10,0), 
	"ID_CONTENAIR" NUMBER(10,0), 
	"QUANTITE_CONSOMMEE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONTENIR
--------------------------------------------------------

  CREATE TABLE "OILPRESSTEAM"."CONTENIR" 
   (	"ID_CONTENAIR" NUMBER(10,0), 
	"ID_COMMANDE" NUMBER(10,0), 
	"QUANTITE_DEMANDEE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FINANCE
--------------------------------------------------------

  CREATE TABLE "OILPRESSTEAM"."FINANCE" 
   (	"ID_TRANSACTION" NUMBER(10,0), 
	"MONTANT" NUMBER(15,2), 
	"DATE_TRANSACTION" DATE, 
	"TYPE_TRANSACTION" VARCHAR2(50 BYTE), 
	"MODE_PAIEMENT" VARCHAR2(50 BYTE), 
	"DESCRIPTION" CLOB, 
	"ID_COMMANDE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("DESCRIPTION") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table INTERVENIR
--------------------------------------------------------

  CREATE TABLE "OILPRESSTEAM"."INTERVENIR" 
   (	"ID_PERSONNEL" NUMBER(10,0), 
	"ID_MACHINE" NUMBER(10,0), 
	"DATE_INTERVENTION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MACHINE
--------------------------------------------------------

  CREATE TABLE "OILPRESSTEAM"."MACHINE" 
   (	"ID_MACHINE" NUMBER(10,0), 
	"NOM_MACHINE" VARCHAR2(100 BYTE), 
	"TYPE_MACHINE" VARCHAR2(50 BYTE), 
	"ETAT_MACHINE" VARCHAR2(50 BYTE), 
	"DATEDERNIEREMAINTENANCE" DATE, 
	"HEURESFONCTIONNEMENT" NUMBER(10,0), 
	"SEUILMAINTENANCE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERSONNEL
--------------------------------------------------------

  CREATE TABLE "OILPRESSTEAM"."PERSONNEL" 
   (	"ID_PERSONNEL" NUMBER(10,0), 
	"NOM_PERSONNEL" VARCHAR2(100 BYTE), 
	"SALAIRE_BRUT" NUMBER(10,2), 
	"ADRESSE" CLOB, 
	"TEL" VARCHAR2(20 BYTE), 
	"EXPERIENCE" NUMBER(5,0), 
	"GRADE" VARCHAR2(50 BYTE), 
	"ROLE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("ADRESSE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table PRODUIRE
--------------------------------------------------------

  CREATE TABLE "OILPRESSTEAM"."PRODUIRE" 
   (	"ID_CONTENAIR" NUMBER(10,0), 
	"ID_MACHINE" NUMBER(10,0), 
	"QUANTITE_PRODUIRE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUIT
--------------------------------------------------------

  CREATE TABLE "OILPRESSTEAM"."PRODUIT" 
   (	"ID_CONTENAIR" NUMBER(10,0), 
	"DATE_PRESS" DATE, 
	"QUANTITE" NUMBER(10,0), 
	"REF" VARCHAR2(50 BYTE), 
	"VISCOSITE" VARCHAR2(50 BYTE), 
	"COULEUR" VARCHAR2(30 BYTE), 
	"TEST" VARCHAR2(100 BYTE), 
	"CAPACITE" NUMBER(10,0), 
	"ID_MACHINE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into OILPRESSTEAM.ARTICLE
SET DEFINE OFF;
REM INSERTING into OILPRESSTEAM.COMMANDE
SET DEFINE OFF;
Insert into OILPRESSTEAM.COMMANDE (ID_COMMANDE,DATE_COMMANDE,ETAT_COMMANDE,NOM_CLIENT,DATE_LIVRAISON,ADRESSE_LIVRAISON,ADRESSE_CLIENT) values ('1',to_date('31/03/26','DD/MM/RR'),'Pending','yassine hablani',to_date('05/04/26','DD/MM/RR'),null,'bardo');
Insert into OILPRESSTEAM.COMMANDE (ID_COMMANDE,DATE_COMMANDE,ETAT_COMMANDE,NOM_CLIENT,DATE_LIVRAISON,ADRESSE_LIVRAISON,ADRESSE_CLIENT) values ('2',to_date('31/03/26','DD/MM/RR'),'Pending','Yassine Hablani',to_date('03/05/26','DD/MM/RR'),null,'Bardo');
REM INSERTING into OILPRESSTEAM.CONSOMMER
SET DEFINE OFF;
REM INSERTING into OILPRESSTEAM.CONTENIR
SET DEFINE OFF;
REM INSERTING into OILPRESSTEAM.FINANCE
SET DEFINE OFF;
REM INSERTING into OILPRESSTEAM.INTERVENIR
SET DEFINE OFF;
REM INSERTING into OILPRESSTEAM.MACHINE
SET DEFINE OFF;
Insert into OILPRESSTEAM.MACHINE (ID_MACHINE,NOM_MACHINE,TYPE_MACHINE,ETAT_MACHINE,DATEDERNIEREMAINTENANCE,HEURESFONCTIONNEMENT,SEUILMAINTENANCE) values ('1','jhqgsjdhqgsd','hdid','mahlouka',null,'20','100');
REM INSERTING into OILPRESSTEAM.PERSONNEL
SET DEFINE OFF;
REM INSERTING into OILPRESSTEAM.PRODUIRE
SET DEFINE OFF;
REM INSERTING into OILPRESSTEAM.PRODUIT
SET DEFINE OFF;
--------------------------------------------------------
--  Constraints for Table CONTENIR
--------------------------------------------------------

  ALTER TABLE "OILPRESSTEAM"."CONTENIR" ADD PRIMARY KEY ("ID_CONTENAIR", "ID_COMMANDE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUIRE
--------------------------------------------------------

  ALTER TABLE "OILPRESSTEAM"."PRODUIRE" ADD PRIMARY KEY ("ID_CONTENAIR", "ID_MACHINE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INTERVENIR
--------------------------------------------------------

  ALTER TABLE "OILPRESSTEAM"."INTERVENIR" ADD PRIMARY KEY ("ID_PERSONNEL", "ID_MACHINE", "DATE_INTERVENTION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONSOMMER
--------------------------------------------------------

  ALTER TABLE "OILPRESSTEAM"."CONSOMMER" ADD PRIMARY KEY ("ID_ARTICLE", "ID_CONTENAIR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MACHINE
--------------------------------------------------------

  ALTER TABLE "OILPRESSTEAM"."MACHINE" ADD PRIMARY KEY ("ID_MACHINE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ARTICLE
--------------------------------------------------------

  ALTER TABLE "OILPRESSTEAM"."ARTICLE" ADD PRIMARY KEY ("ID_ARTICLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PERSONNEL
--------------------------------------------------------

  ALTER TABLE "OILPRESSTEAM"."PERSONNEL" ADD PRIMARY KEY ("ID_PERSONNEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMANDE
--------------------------------------------------------

  ALTER TABLE "OILPRESSTEAM"."COMMANDE" ADD PRIMARY KEY ("ID_COMMANDE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FINANCE
--------------------------------------------------------

  ALTER TABLE "OILPRESSTEAM"."FINANCE" ADD PRIMARY KEY ("ID_TRANSACTION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUIT
--------------------------------------------------------

  ALTER TABLE "OILPRESSTEAM"."PRODUIT" ADD PRIMARY KEY ("ID_CONTENAIR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONSOMMER
--------------------------------------------------------

  ALTER TABLE "OILPRESSTEAM"."CONSOMMER" ADD CONSTRAINT "FK_CONS_ART" FOREIGN KEY ("ID_ARTICLE")
	  REFERENCES "OILPRESSTEAM"."ARTICLE" ("ID_ARTICLE") ENABLE;
  ALTER TABLE "OILPRESSTEAM"."CONSOMMER" ADD CONSTRAINT "FK_CONS_PROD" FOREIGN KEY ("ID_CONTENAIR")
	  REFERENCES "OILPRESSTEAM"."PRODUIT" ("ID_CONTENAIR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONTENIR
--------------------------------------------------------

  ALTER TABLE "OILPRESSTEAM"."CONTENIR" ADD CONSTRAINT "FK_CONT_COM" FOREIGN KEY ("ID_COMMANDE")
	  REFERENCES "OILPRESSTEAM"."COMMANDE" ("ID_COMMANDE") ENABLE;
  ALTER TABLE "OILPRESSTEAM"."CONTENIR" ADD CONSTRAINT "FK_CONT_PROD" FOREIGN KEY ("ID_CONTENAIR")
	  REFERENCES "OILPRESSTEAM"."PRODUIT" ("ID_CONTENAIR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FINANCE
--------------------------------------------------------

  ALTER TABLE "OILPRESSTEAM"."FINANCE" ADD CONSTRAINT "FK_COMMANDE" FOREIGN KEY ("ID_COMMANDE")
	  REFERENCES "OILPRESSTEAM"."COMMANDE" ("ID_COMMANDE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INTERVENIR
--------------------------------------------------------

  ALTER TABLE "OILPRESSTEAM"."INTERVENIR" ADD CONSTRAINT "FK_INT_MACH" FOREIGN KEY ("ID_MACHINE")
	  REFERENCES "OILPRESSTEAM"."MACHINE" ("ID_MACHINE") ENABLE;
  ALTER TABLE "OILPRESSTEAM"."INTERVENIR" ADD CONSTRAINT "FK_INT_PERS" FOREIGN KEY ("ID_PERSONNEL")
	  REFERENCES "OILPRESSTEAM"."PERSONNEL" ("ID_PERSONNEL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUIRE
--------------------------------------------------------

  ALTER TABLE "OILPRESSTEAM"."PRODUIRE" ADD CONSTRAINT "FK_PROD_CONT" FOREIGN KEY ("ID_CONTENAIR")
	  REFERENCES "OILPRESSTEAM"."PRODUIT" ("ID_CONTENAIR") ENABLE;
  ALTER TABLE "OILPRESSTEAM"."PRODUIRE" ADD CONSTRAINT "FK_PROD_MACH" FOREIGN KEY ("ID_MACHINE")
	  REFERENCES "OILPRESSTEAM"."MACHINE" ("ID_MACHINE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUIT
--------------------------------------------------------

  ALTER TABLE "OILPRESSTEAM"."PRODUIT" ADD CONSTRAINT "FK_MACHINE" FOREIGN KEY ("ID_MACHINE")
	  REFERENCES "OILPRESSTEAM"."MACHINE" ("ID_MACHINE") ENABLE;
